name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
<<<<<<< HEAD
    - name: Text Cleanup Tests
      id: text-cleanup-tests
=======
    - name: Step Streaks Tests
      id: step-streaks-tests
>>>>>>> 8c49106e810e407fc32ff40afcf5d2fcb2c1bc35
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
<<<<<<< HEAD
        TEXT-CLEANUP-TESTS_RESULTS: "${{steps.text-cleanup-tests.outputs.result}}"
      with:
        runners: text-cleanup-tests
=======
        STEP-STREAKS-TESTS_RESULTS: "${{steps.step-streaks-tests.outputs.result}}"
      with:
        runners: step-streaks-tests
>>>>>>> 8c49106e810e407fc32ff40afcf5d2fcb2c1bc35
