name: Autograding Tests

'on':
  - push
  - pull_request
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      # Run pytest with PYTHONPATH
      - name: Run tests
        run: |
          echo "Adding src/ to PYTHONPATH"
          export PYTHONPATH=$GITHUB_WORKSPACE
          python -m pytest -q --tb=short
