name: tests
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies (pytest + optional requirements)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      # Run pytest with PYTHONPATH
      - name: Run pytest
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python -m pytest -q --tb=short
